export const redirects = {
  "/hosts": "/gpu-workloads",
  "/clients": "/gpu-providers",
  "/deploy": "https://deploy.nosana.com/",
  "/stake": "https://stake.nosana.com/",
  "/team": "/about",
  "/token": "/nosana-token",
  "/learn": "https://learn.nosana.com/",
  "/docs": "https://learn.nosana.com/",
  "/brand": "/brand-assets",

  "/x": "https://x.com/nosana_ai",
  "/twitter": "https://x.com/nosana_ai",
  "/linkedin": "https://www.linkedin.com/company/nosana",
  "/medium": "https://nosana.medium.com/",
  "/github": "https://github.com/nosana-ci",
  "/telegram": "https://t.me/NosanaCompute",
  "/discord": "https://discord.gg/nosana-ai",
  "/youtube": "https://www.youtube.com/@NosanaAI",
  "/reddit": "https://www.reddit.com/r/Nosana_AI/",

  "/blog/nosana_opengpu": "/blog/nosana-opengpu-expanding-access-to-ai-compute",
  "/blog/january_on_nosana": "/blog/january-on-nosana-milestones-momentum-whats-next",
  "/blog/2025_at_nosana_a_year_in_review": "/blog/2025-at-nosana-a-year-in-review",
  "/blog/nosana_kit": "/blog/introducing-nosana-kit-the-comprehensive-2-0-toolchain-for-nosana",
  "/blog/wrapped_2025": "/blog/nosana-2025-from-testnets-to-real-world-compute",
  "/blog/nosvember_recap": "/blog/the-heart-of-nosana-nosvember-2025-recap",
  "/blog/grants_announcement": "/blog/the-nosana-grants-program-fueling-the-next-wave-of-ai-builders-vibers-and-dreamers",
  "/blog/agent_recap_2": "/blog/agent-102-recap-mcp-mastra-and-the-next-wave-of-ai-builders",
  "/blog/nosana_monthly_november": "/blog/nosana-monthly-november-edition",
  "/blog/deployment_manager_2": "/blog/visual-command-center-managing-deployments-with-nosanas-dashboard",
  "/blog/folding-at-home": "/blog/nosanas-spare-gpu-capacity-is-now-powering-scientific-research",
  "/blog/newsletter-october-2025": "/blog/nosana-monthly-october-edition",
  "/blog/voting": "/blog/from-proposal-to-vote-how-nnp-0001-will-be-decided",
  "/blog/nosvember": "/blog/nosvember-games-a-month-of-celebration-for-the-nosana-community",
  "/blog/tokenomics-proposal": "/blog/from-yield-to-growth-aligning-nos-rewards-with-real-usage",
  "/blog/deployment_manager_1": "/blog/elevating-the-deployment-experience-introducing-nosanas-new-deployment-manager",
  "/blog/agent_challenge_102": "/blog/builders-challenge-agents-102",
  "/blog/asian_expansion": "/blog/nosana-expands-across-asia-powering-the-future-of-ai-infrastructure",
  "/blog/start_up_economics": "/blog/how-were-helping-ai-startups-cut-costs-by-67-with-open-source-models",
  "/blog/agent-101-recap-how-builders-took-on-the-nosana-challenge": "/blog/agent_recap",
  "/blog/agent_challenge": "/blog/builders-challenge-agents-101",
  "/blog/nos_challenge": "/blog/builders-challenge-create-a-nosana-template",
  "/blog/nosana_swapping_priority_fees": "/blog/introducing-swapping-and-priority-fees",
};
